# Generated by Django 5.2.10 on 2026-01-30 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=200, verbose_name='报告名称')),
                ('report_type', models.CharField(choices=[('test_summary', '测试总结报告'), ('api_test', 'API测试报告'), ('perf_test', '性能测试报告'), ('bug_analysis', 'Bug分析报告'), ('custom', '自定义报告')], default='custom', max_length=50, verbose_name='报告类型')),
                ('description', models.TextField(blank=True, verbose_name='报告描述')),
                ('report_data', models.JSONField(blank=True, default=dict, verbose_name='报告数据')),
                ('file_path', models.FileField(blank=True, upload_to='reports/%Y/%m/', verbose_name='报告文件')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='文件大小(字节)')),
                ('format', models.CharField(choices=[('html', 'HTML'), ('pdf', 'PDF'), ('excel', 'Excel'), ('json', 'JSON')], default='html', max_length=20, verbose_name='报告格式')),
                ('status', models.CharField(choices=[('generating', '生成中'), ('completed', '已完成'), ('failed', '生成失败')], default='generating', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='查看次数')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='下载次数')),
            ],
            options={
                'verbose_name': '报告',
                'verbose_name_plural': '报告',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=200, verbose_name='模板名称')),
                ('template_type', models.CharField(choices=[('test_summary', '测试总结报告'), ('api_test', 'API测试报告'), ('perf_test', '性能测试报告'), ('bug_analysis', 'Bug分析报告'), ('custom', '自定义报告')], default='custom', max_length=50, verbose_name='模板类型')),
                ('description', models.TextField(blank=True, verbose_name='模板描述')),
                ('content_template', models.TextField(help_text='支持Jinja2模板语法', verbose_name='内容模板')),
                ('style_css', models.TextField(blank=True, verbose_name='样式CSS')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认模板')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '报告模板',
                'verbose_name_plural': '报告模板',
                'ordering': ['-created_at'],
            },
        ),
    ]
