# Generated by Django 5.2.10 on 2026-01-30 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeishuChatBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('chat_id', models.CharField(max_length=200, verbose_name='飞书群聊ID')),
                ('chat_name', models.CharField(blank=True, max_length=200, verbose_name='群聊名称')),
                ('notify_bug_created', models.BooleanField(default=True, verbose_name='Bug创建通知')),
                ('notify_bug_status_change', models.BooleanField(default=True, verbose_name='Bug状态变更通知')),
                ('notify_test_completed', models.BooleanField(default=True, verbose_name='测试完成通知')),
            ],
            options={
                'verbose_name': '飞书群聊绑定',
                'verbose_name_plural': '飞书群聊绑定',
            },
        ),
        migrations.CreateModel(
            name='FeishuConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=200, verbose_name='配置名称')),
                ('app_id', models.CharField(max_length=200, verbose_name='App ID')),
                ('app_secret', models.CharField(max_length=500, verbose_name='App Secret')),
                ('verification_token', models.CharField(blank=True, max_length=500, verbose_name='Verification Token')),
                ('encrypt_key', models.CharField(blank=True, help_text='群聊机器人安全设置中的签名校验密钥，用于生成请求签名', max_length=500, verbose_name='Encrypt Key')),
                ('webhook_url', models.URLField(blank=True, help_text='飞书群聊机器人的Webhook地址，格式: https://open.feishu.cn/open-apis/bot/v2/hook/xxxxxx', verbose_name='Webhook URL')),
                ('default_chat_id', models.CharField(blank=True, max_length=200, verbose_name='默认群聊ID')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '飞书配置',
                'verbose_name_plural': '飞书配置',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeishuMessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=200, verbose_name='模板名称')),
                ('template_type', models.CharField(choices=[('bug_created', 'Bug创建'), ('bug_assigned', 'Bug分配'), ('bug_resolved', 'Bug解决'), ('bug_closed', 'Bug关闭'), ('bug_reopened', 'Bug重新打开'), ('api_test_completed', 'API测试完成'), ('perf_test_completed', '性能测试完成'), ('custom', '自定义')], default='custom', max_length=50, verbose_name='模板类型')),
                ('description', models.TextField(blank=True, verbose_name='模板描述')),
                ('template_content', models.JSONField(default=dict, verbose_name='模板内容')),
                ('variables', models.JSONField(default=dict, help_text='模板中使用的变量说明', verbose_name='模板变量')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认模板')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '飞书消息模板',
                'verbose_name_plural': '飞书消息模板',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeishuNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('message_type', models.CharField(choices=[('text', '文本消息'), ('card', '卡片消息'), ('image', '图片消息')], max_length=20, verbose_name='消息类型')),
                ('chat_id', models.CharField(blank=True, max_length=200, verbose_name='群聊ID')),
                ('user_id', models.CharField(blank=True, max_length=200, verbose_name='用户ID')),
                ('content', models.JSONField(verbose_name='消息内容')),
                ('related_object_type', models.CharField(blank=True, max_length=100, verbose_name='关联对象类型')),
                ('related_object_id', models.CharField(blank=True, max_length=100, verbose_name='关联对象ID')),
                ('status', models.CharField(choices=[('pending', '发送中'), ('success', '发送成功'), ('failed', '发送失败')], default='pending', max_length=20, verbose_name='状态')),
                ('response_data', models.JSONField(blank=True, default=dict, verbose_name='响应数据')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
            ],
            options={
                'verbose_name': '飞书通知日志',
                'verbose_name_plural': '飞书通知日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
