# Generated by Django 5.2.10 on 2026-01-30 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerfTestJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('description', models.TextField(blank=True, verbose_name='任务描述')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('passed', '已通过'), ('failed', '已失败'), ('error', '执行错误'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('trigger_type', models.CharField(choices=[('manual', '手动触发'), ('scheduled', '定时触发'), ('ci', 'CI集成')], default='manual', max_length=20, verbose_name='触发方式')),
                ('concurrent_users', models.PositiveIntegerField(blank=True, null=True, verbose_name='并发用户数')),
                ('test_duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='测试时长(秒)')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('total_requests', models.PositiveIntegerField(blank=True, null=True, verbose_name='总请求数')),
                ('avg_response_time', models.FloatField(blank=True, null=True, verbose_name='平均响应时间(ms)')),
                ('min_response_time', models.FloatField(blank=True, null=True, verbose_name='最小响应时间(ms)')),
                ('max_response_time', models.FloatField(blank=True, null=True, verbose_name='最大响应时间(ms)')),
                ('error_rate', models.FloatField(blank=True, null=True, verbose_name='错误率')),
                ('requests_per_second', models.FloatField(blank=True, null=True, verbose_name='每秒请求数')),
                ('passed_criteria', models.BooleanField(blank=True, null=True, verbose_name='是否通过标准')),
                ('report_data', models.JSONField(blank=True, default=dict, verbose_name='报告数据')),
                ('report_file', models.FileField(blank=True, upload_to='perf_reports/%Y/%m/', verbose_name='报告文件')),
            ],
            options={
                'verbose_name': '性能测试任务',
                'verbose_name_plural': '性能测试任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerfTestMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('timestamp', models.DateTimeField(verbose_name='时间戳')),
                ('total_requests', models.PositiveIntegerField(verbose_name='总请求数')),
                ('failed_requests', models.PositiveIntegerField(verbose_name='失败请求数')),
                ('avg_response_time', models.FloatField(verbose_name='平均响应时间(ms)')),
                ('min_response_time', models.FloatField(verbose_name='最小响应时间(ms)')),
                ('max_response_time', models.FloatField(verbose_name='最大响应时间(ms)')),
                ('p50_response_time', models.FloatField(verbose_name='P50响应时间(ms)')),
                ('p95_response_time', models.FloatField(verbose_name='P95响应时间(ms)')),
                ('p99_response_time', models.FloatField(verbose_name='P99响应时间(ms)')),
                ('requests_per_second', models.FloatField(verbose_name='每秒请求数')),
                ('bytes_per_second', models.FloatField(verbose_name='每秒字节数')),
                ('current_users', models.PositiveIntegerField(verbose_name='当前用户数')),
            ],
            options={
                'verbose_name': '性能测试指标',
                'verbose_name_plural': '性能测试指标',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PerfTestScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=200, verbose_name='场景名称')),
                ('description', models.TextField(blank=True, verbose_name='场景描述')),
                ('scenario_type', models.CharField(choices=[('load', '负载测试'), ('stress', '压力测试'), ('spike', '尖峰测试'), ('endurance', '耐力测试'), ('scalability', '可扩展性测试')], default='load', max_length=20, verbose_name='场景类型')),
                ('target_url', models.URLField(verbose_name='目标URL')),
                ('http_method', models.CharField(default='GET', max_length=10, verbose_name='HTTP方法')),
                ('headers', models.JSONField(blank=True, default=dict, verbose_name='请求头')),
                ('body', models.TextField(blank=True, verbose_name='请求体')),
                ('concurrent_users', models.PositiveIntegerField(default=10, verbose_name='并发用户数')),
                ('ramp_up_time', models.PositiveIntegerField(default=60, verbose_name='启动时间(秒)')),
                ('test_duration', models.PositiveIntegerField(default=300, verbose_name='测试时长(秒)')),
                ('success_criteria', models.JSONField(blank=True, default=dict, help_text='如: {"avg_response_time": 1000, "error_rate": 0.01}', verbose_name='成功标准')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '性能测试场景',
                'verbose_name_plural': '性能测试场景',
                'ordering': ['-created_at'],
            },
        ),
    ]
