# Generated by Django 5.2.10 on 2026-01-30 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('status_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='状态变更时间')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('code', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='项目编码')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('project_type', models.CharField(choices=[('web', 'Web应用'), ('mobile', '移动应用'), ('desktop', '桌面应用'), ('api', 'API服务'), ('embedded', '嵌入式系统'), ('other', '其他')], default='web', max_length=20, verbose_name='项目类型')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('urgent', '紧急')], default='medium', max_length=20, verbose_name='优先级')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '进行中'), ('paused', '已暂停'), ('completed', '已完成'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('config', models.JSONField(blank=True, default=dict, help_text='项目级别的配置，如测试环境、通知设置等', verbose_name='项目配置')),
                ('jira_project_key', models.CharField(blank=True, max_length=50, verbose_name='JIRA项目Key')),
                ('git_repository', models.URLField(blank=True, verbose_name='Git仓库地址')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=100, verbose_name='环境名称')),
                ('env_type', models.CharField(choices=[('dev', '开发环境'), ('test', '测试环境'), ('staging', '预发布环境'), ('prod', '生产环境')], default='test', max_length=20, verbose_name='环境类型')),
                ('base_url', models.URLField(verbose_name='基础URL')),
                ('description', models.TextField(blank=True, verbose_name='环境描述')),
                ('variables', models.JSONField(blank=True, default=dict, help_text='环境特定的变量，如数据库连接、API密钥等', verbose_name='环境变量')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '项目环境',
                'verbose_name_plural': '项目环境',
                'ordering': ['env_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', '所有者'), ('manager', '管理员'), ('tester', '测试工程师'), ('developer', '开发工程师'), ('viewer', '访客')], default='tester', max_length=20, verbose_name='角色')),
                ('permissions', models.JSONField(blank=True, default=list, help_text='成员在项目中的具体权限', verbose_name='权限列表')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
            ],
            options={
                'verbose_name': '项目成员',
                'verbose_name_plural': '项目成员',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=200, verbose_name='里程碑名称')),
                ('description', models.TextField(blank=True, verbose_name='里程碑描述')),
                ('status', models.CharField(choices=[('pending', '待开始'), ('in_progress', '进行中'), ('completed', '已完成'), ('delayed', '已延期')], default='pending', max_length=20, verbose_name='状态')),
                ('planned_date', models.DateField(blank=True, null=True, verbose_name='计划日期')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='实际日期')),
            ],
            options={
                'verbose_name': '项目里程碑',
                'verbose_name_plural': '项目里程碑',
                'ordering': ['planned_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('version', models.CharField(max_length=50, verbose_name='版本号')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='版本名称')),
                ('description', models.TextField(blank=True, verbose_name='版本描述')),
                ('status', models.CharField(choices=[('planning', '规划中'), ('developing', '开发中'), ('testing', '测试中'), ('released', '已发布'), ('archived', '已归档')], default='planning', max_length=20, verbose_name='状态')),
                ('planned_start_date', models.DateField(blank=True, null=True, verbose_name='计划开始日期')),
                ('planned_end_date', models.DateField(blank=True, null=True, verbose_name='计划结束日期')),
                ('actual_start_date', models.DateField(blank=True, null=True, verbose_name='实际开始日期')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='实际结束日期')),
                ('scope', models.TextField(blank=True, help_text='该版本包含的功能范围', verbose_name='版本范围')),
            ],
            options={
                'verbose_name': '项目版本',
                'verbose_name_plural': '项目版本',
                'ordering': ['-created_at'],
            },
        ),
    ]
