# Generated by Django 5.2.10 on 2026-01-30 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=200, verbose_name='配置名称')),
                ('api_key', models.CharField(blank=True, max_length=500, verbose_name='API Key')),
                ('api_secret', models.CharField(blank=True, max_length=500, verbose_name='API Secret')),
                ('custom_base_url', models.URLField(blank=True, verbose_name='自定义基础URL')),
                ('default_model', models.CharField(blank=True, max_length=100, verbose_name='默认模型')),
                ('max_tokens', models.PositiveIntegerField(default=2048, verbose_name='最大Token数')),
                ('temperature', models.FloatField(default=0.7, verbose_name='Temperature')),
                ('top_p', models.FloatField(default=1.0, verbose_name='Top P')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='使用次数')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最后使用时间')),
            ],
            options={
                'verbose_name': '大模型配置',
                'verbose_name_plural': '大模型配置',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LLMConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='对话标题')),
                ('context', models.JSONField(blank=True, default=list, verbose_name='对话上下文')),
                ('message_count', models.PositiveIntegerField(default=0, verbose_name='消息数')),
                ('token_usage', models.PositiveIntegerField(default=0, verbose_name='Token使用量')),
            ],
            options={
                'verbose_name': '大模型对话',
                'verbose_name_plural': '大模型对话',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LLMMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('role', models.CharField(choices=[('system', '系统'), ('user', '用户'), ('assistant', '助手')], max_length=20, verbose_name='角色')),
                ('content', models.TextField(verbose_name='内容')),
                ('prompt_tokens', models.PositiveIntegerField(default=0, verbose_name='Prompt Tokens')),
                ('completion_tokens', models.PositiveIntegerField(default=0, verbose_name='Completion Tokens')),
                ('total_tokens', models.PositiveIntegerField(default=0, verbose_name='Total Tokens')),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='响应时间(ms)')),
            ],
            options={
                'verbose_name': '大模型消息',
                'verbose_name_plural': '大模型消息',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LLMProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('code', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic Claude'), ('google', 'Google Gemini'), ('baidu', '百度文心一言'), ('alibaba', '阿里通义千问'), ('xunfei', '讯飞星火'), ('zhipu', '智谱AI'), ('moonshot', '月之暗面Kimi'), ('deepseek', 'DeepSeek'), ('minimax', 'MiniMax'), ('zeroone', '零一万物'), ('custom', '自定义')], max_length=50, unique=True, verbose_name='提供商代码')),
                ('name', models.CharField(max_length=100, verbose_name='提供商名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('base_url', models.URLField(blank=True, verbose_name='基础URL')),
                ('api_key_required', models.BooleanField(default=True, verbose_name='需要API Key')),
                ('api_secret_required', models.BooleanField(default=False, verbose_name='需要API Secret')),
                ('supported_models', models.JSONField(default=list, help_text='支持的模型列表', verbose_name='支持的模型')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '大模型提供商',
                'verbose_name_plural': '大模型提供商',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LLMTestGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('generation_type', models.CharField(choices=[('testcase', '测试用例'), ('api_test', 'API测试'), ('bug_analysis', 'Bug分析'), ('code_review', '代码审查')], max_length=20, verbose_name='生成类型')),
                ('prompt', models.TextField(verbose_name='提示词')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='上下文')),
                ('result', models.TextField(verbose_name='生成结果')),
                ('prompt_tokens', models.PositiveIntegerField(default=0, verbose_name='Prompt Tokens')),
                ('completion_tokens', models.PositiveIntegerField(default=0, verbose_name='Completion Tokens')),
                ('total_tokens', models.PositiveIntegerField(default=0, verbose_name='Total Tokens')),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='响应时间(ms)')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='评分')),
                ('feedback', models.TextField(blank=True, verbose_name='反馈')),
            ],
            options={
                'verbose_name': 'AI生成记录',
                'verbose_name_plural': 'AI生成记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
