# Generated by Django 5.2.10 on 2026-01-30 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('status_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='状态变更时间')),
                ('case_no', models.CharField(db_index=True, max_length=100, verbose_name='用例编号')),
                ('name', models.CharField(max_length=500, verbose_name='用例名称')),
                ('description', models.TextField(blank=True, verbose_name='用例描述')),
                ('case_type', models.CharField(choices=[('functional', '功能测试'), ('performance', '性能测试'), ('security', '安全测试'), ('compatibility', '兼容性测试'), ('usability', '易用性测试'), ('api', '接口测试'), ('ui', 'UI测试'), ('other', '其他')], default='functional', max_length=20, verbose_name='用例类型')),
                ('priority', models.CharField(choices=[('p0', 'P0-最高'), ('p1', 'P1-高'), ('p2', 'P2-中'), ('p3', 'P3-低')], default='p2', max_length=10, verbose_name='优先级')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待执行'), ('running', '执行中'), ('passed', '已通过'), ('failed', '已失败'), ('blocked', '已阻塞'), ('skipped', '已跳过')], default='draft', max_length=20, verbose_name='状态')),
                ('preconditions', models.TextField(blank=True, verbose_name='前置条件')),
                ('steps', models.JSONField(default=list, help_text='JSON格式测试步骤', verbose_name='测试步骤')),
                ('expected_result', models.TextField(verbose_name='预期结果')),
                ('actual_result', models.TextField(blank=True, verbose_name='实际结果')),
                ('module', models.CharField(blank=True, max_length=200, verbose_name='所属模块')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('last_executed_at', models.DateTimeField(blank=True, null=True, verbose_name='最后执行时间')),
                ('execution_count', models.PositiveIntegerField(default=0, verbose_name='执行次数')),
                ('pass_count', models.PositiveIntegerField(default=0, verbose_name='通过次数')),
                ('fail_count', models.PositiveIntegerField(default=0, verbose_name='失败次数')),
                ('related_requirements', models.JSONField(blank=True, default=list, verbose_name='关联需求')),
                ('related_bugs', models.JSONField(blank=True, default=list, verbose_name='关联Bug')),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=200, verbose_name='计划名称')),
                ('description', models.TextField(blank=True, verbose_name='计划描述')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('planned_start_date', models.DateTimeField(blank=True, null=True, verbose_name='计划开始时间')),
                ('planned_end_date', models.DateTimeField(blank=True, null=True, verbose_name='计划结束时间')),
                ('actual_start_date', models.DateTimeField(blank=True, null=True, verbose_name='实际开始时间')),
                ('actual_end_date', models.DateTimeField(blank=True, null=True, verbose_name='实际结束时间')),
                ('total_cases', models.PositiveIntegerField(default=0, verbose_name='总用例数')),
                ('passed_cases', models.PositiveIntegerField(default=0, verbose_name='通过数')),
                ('failed_cases', models.PositiveIntegerField(default=0, verbose_name='失败数')),
                ('blocked_cases', models.PositiveIntegerField(default=0, verbose_name='阻塞数')),
            ],
            options={
                'verbose_name': '测试计划',
                'verbose_name_plural': '测试计划',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=200, verbose_name='套件名称')),
                ('description', models.TextField(blank=True, verbose_name='套件描述')),
            ],
            options={
                'verbose_name': '测试套件',
                'verbose_name_plural': '测试套件',
                'ordering': ['-created_at'],
            },
        ),
    ]
