# Generated by Django 5.2.10 on 2026-01-30 02:02

import apps.users.managers
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='权限名称')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='权限编码')),
                ('category', models.CharField(choices=[('user', '用户管理'), ('project', '项目管理'), ('testcase', '用例管理'), ('bug', 'Bug管理'), ('apitest', '接口测试'), ('perftest', '性能测试'), ('report', '报告管理'), ('system', '系统设置')], max_length=20, verbose_name='权限分类')),
                ('description', models.TextField(blank=True, verbose_name='权限描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='角色名称')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='角色编码')),
                ('description', models.TextField(blank=True, verbose_name='角色描述')),
                ('role_type', models.CharField(choices=[('system', '系统角色'), ('custom', '自定义角色')], default='custom', max_length=20, verbose_name='角色类型')),
                ('permissions', models.JSONField(default=list, help_text='角色拥有的权限代码列表', verbose_name='权限列表')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认角色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(help_text='必填。150个字符以内。只能包含字母、数字和@/./+/-/_', max_length=150, unique=True, verbose_name='用户名')),
                ('email', models.EmailField(help_text='用于登录和接收通知', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, help_text='用于接收短信通知', max_length=20, verbose_name='手机号')),
                ('nickname', models.CharField(blank=True, max_length=50, verbose_name='昵称')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='头像')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='部门')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='职位')),
                ('user_type', models.CharField(choices=[('admin', '管理员'), ('tester', '测试工程师'), ('developer', '开发工程师'), ('pm', '产品经理'), ('viewer', '访客')], default='tester', max_length=20, verbose_name='用户类型')),
                ('status', models.CharField(choices=[('active', '活跃'), ('inactive', '未激活'), ('suspended', '已停用')], default='active', max_length=20, verbose_name='状态')),
                ('is_staff', models.BooleanField(default=False, help_text='决定用户是否可以登录管理后台', verbose_name='管理员状态')),
                ('is_active', models.BooleanField(default=True, help_text='决定用户是否可以登录系统', verbose_name='激活状态')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='注册时间')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='最后登录IP')),
                ('last_activity_at', models.DateTimeField(blank=True, null=True, verbose_name='最后活动时间')),
                ('feishu_user_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='飞书用户ID')),
                ('feishu_open_id', models.CharField(blank=True, max_length=100, verbose_name='飞书OpenID')),
                ('preferences', models.JSONField(blank=True, default=dict, help_text='用户个性化设置，如主题、语言、通知偏好等', verbose_name='偏好设置')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', apps.users.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_type', models.CharField(choices=[('password', '密码登录'), ('sso', '单点登录'), ('feishu', '飞书登录'), ('ldap', 'LDAP登录')], default='password', max_length=20, verbose_name='登录方式')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('locked', '账户锁定')], max_length=20, verbose_name='登录状态')),
                ('fail_reason', models.CharField(blank=True, max_length=255, verbose_name='失败原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登录时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '登录日志',
                'verbose_name_plural': '登录日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='分配时间')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL, verbose_name='分配人')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_user_roles', to='projects.project', verbose_name='项目')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_users', to='users.role', verbose_name='角色')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户角色',
                'verbose_name_plural': '用户角色',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username', 'is_active'], name='users_user_usernam_6cca96_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'is_active'], name='users_user_email_3f6199_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type', 'status'], name='users_user_user_ty_a7b564_idx'),
        ),
        migrations.AddIndex(
            model_name='userloginlog',
            index=models.Index(fields=['user', 'created_at'], name='users_userl_user_id_c9452d_idx'),
        ),
        migrations.AddIndex(
            model_name='userloginlog',
            index=models.Index(fields=['ip_address', 'created_at'], name='users_userl_ip_addr_072ed9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role', 'project')},
        ),
    ]
