# Generated by Django 5.2.10 on 2026-01-30 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=200, verbose_name='API名称')),
                ('description', models.TextField(blank=True, verbose_name='API描述')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS')], default='GET', max_length=10, verbose_name='请求方法')),
                ('path', models.CharField(max_length=1000, verbose_name='请求路径')),
                ('headers', models.JSONField(blank=True, default=dict, verbose_name='请求头')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='URL参数')),
                ('content_type', models.CharField(choices=[('application/json', 'application/json'), ('application/x-www-form-urlencoded', 'application/x-www-form-urlencoded'), ('multipart/form-data', 'multipart/form-data'), ('text/plain', 'text/plain'), ('text/html', 'text/html'), ('application/xml', 'application/xml')], default='application/json', max_length=100, verbose_name='Content-Type')),
                ('body', models.JSONField(blank=True, default=dict, verbose_name='请求体')),
                ('body_raw', models.TextField(blank=True, verbose_name='原始请求体')),
                ('auth_type', models.CharField(blank=True, max_length=50, verbose_name='认证类型')),
                ('auth_config', models.JSONField(blank=True, default=dict, verbose_name='认证配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': 'API定义',
                'verbose_name_plural': 'API定义',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApiTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=200, verbose_name='用例名称')),
                ('description', models.TextField(blank=True, verbose_name='用例描述')),
                ('override_headers', models.JSONField(blank=True, default=dict, verbose_name='覆盖请求头')),
                ('override_params', models.JSONField(blank=True, default=dict, verbose_name='覆盖URL参数')),
                ('override_body', models.JSONField(blank=True, default=dict, verbose_name='覆盖请求体')),
                ('expected_status', models.IntegerField(default=200, verbose_name='预期状态码')),
                ('expected_headers', models.JSONField(blank=True, default=dict, verbose_name='预期响应头')),
                ('expected_body', models.JSONField(blank=True, default=dict, verbose_name='预期响应体')),
                ('validation_rules', models.JSONField(blank=True, default=list, help_text='JSON Schema验证规则', verbose_name='验证规则')),
                ('setup_script', models.TextField(blank=True, help_text='执行请求前的Python脚本', verbose_name='前置脚本')),
                ('teardown_script', models.TextField(blank=True, help_text='执行请求后的Python脚本', verbose_name='后置脚本')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': 'API测试用例',
                'verbose_name_plural': 'API测试用例',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApiTestJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('description', models.TextField(blank=True, verbose_name='任务描述')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('passed', '已通过'), ('failed', '已失败'), ('error', '执行错误'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('trigger_type', models.CharField(choices=[('manual', '手动触发'), ('scheduled', '定时触发'), ('webhook', 'Webhook触发'), ('ci', 'CI集成')], default='manual', max_length=20, verbose_name='触发方式')),
                ('total_cases', models.PositiveIntegerField(default=0, verbose_name='总用例数')),
                ('passed_cases', models.PositiveIntegerField(default=0, verbose_name='通过数')),
                ('failed_cases', models.PositiveIntegerField(default=0, verbose_name='失败数')),
                ('error_cases', models.PositiveIntegerField(default=0, verbose_name='错误数')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='执行时长(秒)')),
                ('result_summary', models.JSONField(blank=True, default=dict, verbose_name='结果摘要')),
                ('report_url', models.URLField(blank=True, verbose_name='报告链接')),
            ],
            options={
                'verbose_name': 'API测试任务',
                'verbose_name_plural': 'API测试任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApiTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('status', models.CharField(choices=[('passed', '通过'), ('failed', '失败'), ('error', '错误'), ('skipped', '跳过')], max_length=20, verbose_name='状态')),
                ('request_url', models.URLField(verbose_name='请求URL')),
                ('request_method', models.CharField(max_length=10, verbose_name='请求方法')),
                ('request_headers', models.JSONField(default=dict, verbose_name='请求头')),
                ('request_body', models.TextField(blank=True, verbose_name='请求体')),
                ('response_status', models.IntegerField(verbose_name='响应状态码')),
                ('response_headers', models.JSONField(default=dict, verbose_name='响应头')),
                ('response_body', models.TextField(blank=True, verbose_name='响应体')),
                ('response_time_ms', models.PositiveIntegerField(verbose_name='响应时间(ms)')),
                ('validation_results', models.JSONField(default=list, verbose_name='验证结果')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('started_at', models.DateTimeField(verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(verbose_name='完成时间')),
                ('duration_ms', models.PositiveIntegerField(verbose_name='执行时长(ms)')),
            ],
            options={
                'verbose_name': 'API测试结果',
                'verbose_name_plural': 'API测试结果',
                'ordering': ['-created_at'],
            },
        ),
    ]
