# Generated by Django 5.2.10 on 2026-01-30 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', '创建'), ('UPDATE', '更新'), ('DELETE', '删除'), ('VIEW', '查看'), ('EXPORT', '导出'), ('IMPORT', '导入'), ('EXECUTE', '执行'), ('APPROVE', '审批'), ('REJECT', '驳回'), ('OTHER', '其他')], max_length=50, verbose_name='操作类型')),
                ('resource_type', models.CharField(max_length=100, verbose_name='资源类型')),
                ('resource_id', models.CharField(max_length=100, verbose_name='资源ID')),
                ('resource_name', models.CharField(blank=True, max_length=255, verbose_name='资源名称')),
                ('old_data', models.JSONField(blank=True, null=True, verbose_name='变更前数据')),
                ('new_data', models.JSONField(blank=True, null=True, verbose_name='变更后数据')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('description', models.TextField(blank=True, verbose_name='操作描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='配置键')),
                ('value', models.TextField(verbose_name='配置值')),
                ('config_type', models.CharField(choices=[('STRING', '字符串'), ('INTEGER', '整数'), ('FLOAT', '浮点数'), ('BOOLEAN', '布尔值'), ('JSON', 'JSON'), ('TEXT', '文本')], default='STRING', max_length=20, verbose_name='配置类型')),
                ('description', models.TextField(blank=True, verbose_name='配置说明')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
                'ordering': ['key'],
            },
        ),
    ]
