# Generated by Django 5.2.10 on 2026-01-30 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('status_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='状态变更时间')),
                ('bug_no', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Bug编号')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('description', models.TextField(verbose_name='详细描述')),
                ('bug_type', models.CharField(choices=[('functional', '功能缺陷'), ('ui', '界面问题'), ('performance', '性能问题'), ('compatibility', '兼容性问题'), ('security', '安全问题'), ('data', '数据问题'), ('other', '其他')], default='functional', max_length=20, verbose_name='Bug类型')),
                ('severity', models.CharField(choices=[('critical', '致命'), ('major', '严重'), ('minor', '一般'), ('trivial', '轻微')], default='minor', max_length=20, verbose_name='严重程度')),
                ('priority', models.CharField(choices=[('urgent', '紧急'), ('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=20, verbose_name='优先级')),
                ('status', models.CharField(choices=[('new', '新建'), ('confirmed', '已确认'), ('in_progress', '处理中'), ('resolved', '已解决'), ('rejected', '已拒绝'), ('closed', '已关闭'), ('reopened', '重新打开')], default='new', max_length=20, verbose_name='状态')),
                ('module', models.CharField(blank=True, max_length=200, verbose_name='所属模块')),
                ('environment', models.CharField(blank=True, max_length=500, verbose_name='发现环境')),
                ('browser', models.CharField(blank=True, max_length=200, verbose_name='浏览器')),
                ('steps_to_reproduce', models.TextField(blank=True, verbose_name='复现步骤')),
                ('expected_result', models.TextField(blank=True, verbose_name='预期结果')),
                ('actual_result', models.TextField(blank=True, verbose_name='实际结果')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='附件')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('resolution', models.TextField(blank=True, verbose_name='解决方案')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
            ],
            options={
                'verbose_name': 'Bug',
                'verbose_name_plural': 'Bug',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BugComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('is_internal', models.BooleanField(default=False, help_text='仅内部人员可见', verbose_name='内部评论')),
            ],
            options={
                'verbose_name': 'Bug评论',
                'verbose_name_plural': 'Bug评论',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BugHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('assign', '分配'), ('resolve', '解决'), ('close', '关闭'), ('reopen', '重新打开'), ('comment', '评论')], max_length=20, verbose_name='操作')),
                ('field', models.CharField(blank=True, max_length=100, verbose_name='字段')),
                ('old_value', models.TextField(blank=True, verbose_name='旧值')),
                ('new_value', models.TextField(blank=True, verbose_name='新值')),
            ],
            options={
                'verbose_name': 'Bug历史',
                'verbose_name_plural': 'Bug历史',
                'ordering': ['-created_at'],
            },
        ),
    ]
